"""empty message

Revision ID: 39cec7836ae9
Revises: 9e805674166c
Create Date: 2022-06-18 11:11:44.231806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39cec7836ae9'
down_revision = '9e805674166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
